version: '0.1'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345678@Abc
  # app:
  #   build: .
  #   depends_on:
  #     - db
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production

volumes:
  postgres_data: